# Generated by Django 3.2.13 on 2022-04-21 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Alphanumeric characters only', max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Alphanumeric characters only.')], verbose_name='username'),
        ),
    ]
