# Generated by Django 3.2.13 on 2022-04-21 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='colour',
            new_name='color',
        ),
    ]
